"""Add forum system models with consistent UUID foreign keys

Revision ID: 1a40770b6cc7
Revises: f89d7b62797d
Create Date: 2025-08-07 14:55:37.557191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a40770b6cc7'
down_revision: Union[str, None] = 'f89d7b62797d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_categories',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_type', sa.Enum('AUTOMATION', 'QUALITY_MANAGEMENT', 'MAINTENANCE', 'ARTIFICIAL_INTELLIGENCE', 'IOT', 'GENERAL', name='forumcategorytype'), nullable=False),
    sa.Column('color_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('topics_count', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forum_categories_active_sort', 'forum_categories', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_forum_categories_name'), 'forum_categories', ['name'], unique=False)
    op.create_table('forum_topics',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('has_best_answer', sa.Boolean(), nullable=False),
    sa.Column('best_answer_post_id', sa.UUID(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_post_id', sa.UUID(), nullable=True),
    sa.Column('last_post_author_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['forum_categories.id'], ),
    sa.ForeignKeyConstraint(['last_post_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forum_topics_activity', 'forum_topics', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_forum_topics_author_id'), 'forum_topics', ['author_id'], unique=False)
    op.create_index('ix_forum_topics_author_org', 'forum_topics', ['author_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_forum_topics_category_id'), 'forum_topics', ['category_id'], unique=False)
    op.create_index(op.f('ix_forum_topics_last_post_author_id'), 'forum_topics', ['last_post_author_id'], unique=False)
    op.create_index('ix_forum_topics_org_category', 'forum_topics', ['organization_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_forum_topics_organization_id'), 'forum_topics', ['organization_id'], unique=False)
    op.create_index('ix_forum_topics_pinned', 'forum_topics', ['is_pinned', 'last_activity_at'], unique=False)
    op.create_index(op.f('ix_forum_topics_title'), 'forum_topics', ['title'], unique=False)
    op.create_table('forum_posts',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('parent_post_id', sa.UUID(), nullable=True),
    sa.Column('is_best_answer', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('replies_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['forum_posts.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_posts_author_id'), 'forum_posts', ['author_id'], unique=False)
    op.create_index('ix_forum_posts_author_org', 'forum_posts', ['author_id', 'organization_id'], unique=False)
    op.create_index('ix_forum_posts_best_answer', 'forum_posts', ['topic_id', 'is_best_answer'], unique=False)
    op.create_index('ix_forum_posts_created', 'forum_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_forum_posts_organization_id'), 'forum_posts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_forum_posts_parent_post_id'), 'forum_posts', ['parent_post_id'], unique=False)
    op.create_index(op.f('ix_forum_posts_topic_id'), 'forum_posts', ['topic_id'], unique=False)
    op.create_index('ix_forum_posts_topic_parent', 'forum_posts', ['topic_id', 'parent_post_id'], unique=False)
    op.create_table('file_metadata_v2',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_metadata_v2_file_id'), 'file_metadata_v2', ['file_id'], unique=True)
    op.create_index(op.f('ix_file_metadata_v2_organization_id'), 'file_metadata_v2', ['organization_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_v2_user_id'), 'file_metadata_v2', ['user_id'], unique=False)
    op.create_table('forum_post_likes',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_post_likes_organization_id'), 'forum_post_likes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_forum_post_likes_post_id'), 'forum_post_likes', ['post_id'], unique=False)
    op.create_index('ix_forum_post_likes_unique', 'forum_post_likes', ['post_id', 'user_id'], unique=True)
    op.create_index('ix_forum_post_likes_user', 'forum_post_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_forum_post_likes_user_id'), 'forum_post_likes', ['user_id'], unique=False)
    op.create_table('forum_topic_likes',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_topic_likes_organization_id'), 'forum_topic_likes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_forum_topic_likes_topic_id'), 'forum_topic_likes', ['topic_id'], unique=False)
    op.create_index('ix_forum_topic_likes_unique', 'forum_topic_likes', ['topic_id', 'user_id'], unique=True)
    op.create_index('ix_forum_topic_likes_user', 'forum_topic_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_forum_topic_likes_user_id'), 'forum_topic_likes', ['user_id'], unique=False)
    op.create_table('forum_topic_views',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forum_topic_views_created', 'forum_topic_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_forum_topic_views_organization_id'), 'forum_topic_views', ['organization_id'], unique=False)
    op.create_index(op.f('ix_forum_topic_views_topic_id'), 'forum_topic_views', ['topic_id'], unique=False)
    op.create_index('ix_forum_topic_views_topic_user', 'forum_topic_views', ['topic_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_forum_topic_views_user_id'), 'forum_topic_views', ['user_id'], unique=False)
    op.drop_index('ix_file_metadata_file_id', table_name='file_metadata')
    op.drop_index('ix_file_metadata_organization_id', table_name='file_metadata')
    op.drop_index('ix_file_metadata_user_id', table_name='file_metadata')
    op.drop_table('file_metadata')
    op.alter_column('user_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_invitations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_invitations', 'job_title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user_invitations', 'department',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user_invitations', 'personal_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index('ix_user_invitations_expires_at', table_name='user_invitations')
    op.drop_constraint('fk_user_invitations_organization', 'user_invitations', type_='foreignkey')
    op.drop_constraint('fk_user_invitations_invited_by', 'user_invitations', type_='foreignkey')
    op.drop_constraint('fk_user_invitations_accepted_by', 'user_invitations', type_='foreignkey')
    op.drop_column('user_invitations', 'is_deleted')
    op.drop_column('user_invitations', 'accepted_by')
    
    # Add circular foreign key constraints after all tables are created
    op.create_foreign_key('fk_forum_topics_best_answer_post', 'forum_topics', 'forum_posts', ['best_answer_post_id'], ['id'])
    op.create_foreign_key('fk_forum_topics_last_post', 'forum_topics', 'forum_posts', ['last_post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop circular foreign key constraints first
    op.drop_constraint('fk_forum_topics_best_answer_post', 'forum_topics', type_='foreignkey')
    op.drop_constraint('fk_forum_topics_last_post', 'forum_topics', type_='foreignkey')
    op.add_column('user_invitations', sa.Column('accepted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('user_invitations', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_user_invitations_accepted_by', 'user_invitations', 'users', ['accepted_by'], ['id'])
    op.create_foreign_key('fk_user_invitations_invited_by', 'user_invitations', 'users', ['invited_by'], ['id'])
    op.create_foreign_key('fk_user_invitations_organization', 'user_invitations', 'organizations', ['organization_id'], ['id'])
    op.create_index('ix_user_invitations_expires_at', 'user_invitations', ['expires_at'], unique=False)
    op.alter_column('user_invitations', 'personal_message',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_invitations', 'department',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('user_invitations', 'job_title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('user_invitations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_invitations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('file_metadata',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('extra_metadata', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='file_metadata_organization_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='file_metadata_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_metadata_pkey')
    )
    op.create_index('ix_file_metadata_user_id', 'file_metadata', ['user_id'], unique=False)
    op.create_index('ix_file_metadata_organization_id', 'file_metadata', ['organization_id'], unique=False)
    op.create_index('ix_file_metadata_file_id', 'file_metadata', ['file_id'], unique=True)
    op.drop_index(op.f('ix_forum_topic_views_user_id'), table_name='forum_topic_views')
    op.drop_index('ix_forum_topic_views_topic_user', table_name='forum_topic_views')
    op.drop_index(op.f('ix_forum_topic_views_topic_id'), table_name='forum_topic_views')
    op.drop_index(op.f('ix_forum_topic_views_organization_id'), table_name='forum_topic_views')
    op.drop_index('ix_forum_topic_views_created', table_name='forum_topic_views')
    op.drop_table('forum_topic_views')
    op.drop_index(op.f('ix_forum_topic_likes_user_id'), table_name='forum_topic_likes')
    op.drop_index('ix_forum_topic_likes_user', table_name='forum_topic_likes')
    op.drop_index('ix_forum_topic_likes_unique', table_name='forum_topic_likes')
    op.drop_index(op.f('ix_forum_topic_likes_topic_id'), table_name='forum_topic_likes')
    op.drop_index(op.f('ix_forum_topic_likes_organization_id'), table_name='forum_topic_likes')
    op.drop_table('forum_topic_likes')
    op.drop_index(op.f('ix_forum_post_likes_user_id'), table_name='forum_post_likes')
    op.drop_index('ix_forum_post_likes_user', table_name='forum_post_likes')
    op.drop_index('ix_forum_post_likes_unique', table_name='forum_post_likes')
    op.drop_index(op.f('ix_forum_post_likes_post_id'), table_name='forum_post_likes')
    op.drop_index(op.f('ix_forum_post_likes_organization_id'), table_name='forum_post_likes')
    op.drop_table('forum_post_likes')
    op.drop_index(op.f('ix_file_metadata_v2_user_id'), table_name='file_metadata_v2')
    op.drop_index(op.f('ix_file_metadata_v2_organization_id'), table_name='file_metadata_v2')
    op.drop_index(op.f('ix_file_metadata_v2_file_id'), table_name='file_metadata_v2')
    op.drop_table('file_metadata_v2')
    op.drop_index(op.f('ix_forum_topics_title'), table_name='forum_topics')
    op.drop_index('ix_forum_topics_pinned', table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_organization_id'), table_name='forum_topics')
    op.drop_index('ix_forum_topics_org_category', table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_last_post_author_id'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_category_id'), table_name='forum_topics')
    op.drop_index('ix_forum_topics_author_org', table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_author_id'), table_name='forum_topics')
    op.drop_index('ix_forum_topics_activity', table_name='forum_topics')
    op.drop_table('forum_topics')
    op.drop_index('ix_forum_posts_topic_parent', table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_topic_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_parent_post_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_organization_id'), table_name='forum_posts')
    op.drop_index('ix_forum_posts_created', table_name='forum_posts')
    op.drop_index('ix_forum_posts_best_answer', table_name='forum_posts')
    op.drop_index('ix_forum_posts_author_org', table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_author_id'), table_name='forum_posts')
    op.drop_table('forum_posts')
    op.drop_index(op.f('ix_forum_categories_name'), table_name='forum_categories')
    op.drop_index('ix_forum_categories_active_sort', table_name='forum_categories')
    op.drop_table('forum_categories')
    # ### end Alembic commands ###
