"""add email verification fields to user model

Revision ID: 1a63bc32c08a
Revises: caaf084743a9
Create Date: 2025-08-05 19:23:33.258777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a63bc32c08a'
down_revision: Union[str, None] = 'caaf084743a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add email_verified column as nullable first, then set default values and make it non-nullable
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set default value for existing users (false for not verified)
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('users', 'email_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
