"""Add supertokens_id field to users table

Revision ID: 8f5515e822b8
Revises: 5154fc59743b
Create Date: 2025-08-04 23:42:19.933212

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8f5515e822b8"
down_revision = "5154fc59743b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ONLY add the supertokens_id column to users table
    op.add_column(
        "users", sa.Column("supertokens_id", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_users_supertokens_id"), "users", ["supertokens_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_supertokens_id"), table_name="users")
    op.drop_column("users", "supertokens_id")
    # ### end Alembic commands ###