"""Add timestamps to file_metadata table

Revision ID: ec3cb1e7ea96
Revises: 7fe6a5f30fde
Create Date: 2025-08-06 02:47:01.189328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3cb1e7ea96'
down_revision: Union[str, None] = '7fe6a5f30fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('file_metadata', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'updated_at')
    op.drop_column('file_metadata', 'created_at')
    # ### end Alembic commands ###
